function SummaryModal({ summaryData, onClose }) {
  const completedCount = summaryData?.completedCount ?? 0
  const tasks = summaryData?.tasks || []
  const briefSummary = summaryData?.briefSummary || 'No summary available.'

  const modalText = [
    `Tasks completed today: ${completedCount}`,
    ...tasks.map((task, index) => `${index + 1}. ${task.title} (${task.priority})`),
    '',
    `Brief summary: ${briefSummary}`
  ].join('\n')

  return (
    <div className="summary-modal">
      <div className="summary-content">
        <div className="modal-header">
          <h2>Daily summary</h2>
          <button className="close-btn" onClick={onClose}>×</button>
        </div>
        <div className="summary-block">
          <h3>Completed today</h3>
          <p>{completedCount} task(s)</p>
          {tasks.length > 0 && (
            <ul className="summary-task-list">
              {tasks.map((task, index) => (
                <li key={`${task.title}-${index}`}>
                  <span>{task.title}</span>
                  <span className={`task-priority priority-${task.priority}`}>{task.priority.toUpperCase()}</span>
                </li>
              ))}
            </ul>
          )}
        </div>
        <div className="summary-text">
          <strong>Brief summary</strong>
          <p>{briefSummary}</p>
        </div>
        <p className="meta-text">
          Summary generated by Groq AI on {new Date().toLocaleDateString()}
        </p>
        <div className="modal-actions">
          <button onClick={() => { navigator.clipboard.writeText(modalText); alert('Copied') }}>Copy</button>
          <button onClick={onClose} className="secondary">Close</button>
        </div>
      </div>
    </div>
  )
}

export default SummaryModal
